### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by nicolas-grekas** [voku/portable-utf8#16]
Hello,

I just discovered your work, congrats for getting into the Unicode handling topic, it's a wonderful topic!
There is one pretty big issue with your project that should be easy to fix if you'd like to: patchwork/utf-8 is licensed under dual Apache2/GPLv2 licences. But your readme says your work is under CC BY 3.0. That is not compatible. I encourage you to change the licence of your own contributions to ensure that they are compatible with the code you're reusing.

Cheers,
Nicolas

**Comment by voku** [comment]
Thanks for your work and thx for the hint. Fixed. :)
