### ISSUE TITLE
Class 'voku\helper\shim\Normalizer' not found

### ISSUE THREAD

**Issue by tatthangnt2** [voku/portable-utf8#22]
My project issue:
PHP Fatal error:  Class 'voku\helper\shim\Normalizer' not found in /home4/vaurenne/public_html/include/voku/helper/Bootup.php on line 539

Please help me?

**Comment by voku** [comment]
Have you installed the package via composer? Or do you use any PSR-autoloader?

**Comment by tatthangnt2** [comment]
Thank for help. But i fixed the issue. I'm insatall the package via composer, so just use require_once in '/voku/helper/Bootup.php' :

public static function filterString($s, $normalization_form = 4 /* n::NFC */, $leading_combining = 'â—Œ')
  {
  	require_once 'shim/Normalizer.php';
    if (false !== strpos($s, "\r")) {
      ...
    }
    ...
    return $s;
  }

**Comment by voku** [comment]
I have added your fix into "Bootup.php", can you please test it, thx! via "dev-master"
