### ISSUE TITLE
Insert fails in utf8 field despite utf8mb4 encoding and running clean

### ISSUE THREAD

**Issue by bizmate** [voku/portable-utf8#47]
#### What is this feature about (expected vs actual behaviour)?
expected the library to clean any non utf8 compliant chars when running clean
#### How can I reproduce it?
1 - run utf8mb4 db with column html http://stackoverflow.com/questions/11936950/inserting-utf-8-encoded-string-into-utf-8-encoded-mysql-table-fails-with-incorr
2 - run insert in longtext field with text from file
[textDebug.txt.tar.gz](https://github.com/voku/portable-utf8/files/520607/textDebug.txt.tar.gz)
 (please unpack the text file)
cleaning the text with call `UTF8::clean($response->getBody(), true, true, true)`
3 - see error SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC1\xAA\xCF\xB5</...' for column 'html'
#### Does it take minutes, hours or days to fix?
unknown
#### Any additional information?
Unsure, please ask and i ll provide all the details i can.

**Comment by voku** [comment]
Hi, I can't reproduce the error ... I have added a new test-cases for "Portable UTF-8" (https://github.com/voku/portable-utf8/commit/c303e09b0ccc7703d6d07638674d6ba28b2cb6cd) and also for "Simple MySQLi" (https://github.com/voku/simple-mysqli/commit/fc8effeaddf59d8c76b96117222b7413071670a4) ... both tests are working as expected.

What class do you use to get the html ($response)? Maybe we will find the error there?

**Comment by bizmate** [comment]
Thanks for writing the test. Guzzle is the client returning the response. I doubt it is the cause of the problem. I wonder if anything is wrong in Doctrine  when running the insert or mysql. I use the latest version of mysql as said above configured with utf8mb4. My table/column is also utf8mb4.

My main doubt was in the output coming out the clean function. If this returns UTF-8 characters then mysql should be able to save them. 

In regards to the above statement are these chars UTF-8 - `\xC1\xAA\xCF\xB5</...` ? Would you have any clue as to why it is failing on them? ( i will need to run a test on mysql directly with a manual insert but in the meantime if u have any idea pls let me know

**Comment by voku** [comment]
... maybe Guzzle don't like the charset in the html "charset=gb2312"? I think "charset=utf-8" should also be compatible?

**Comment by bizmate** [comment]
i think utf-8 should should include others like gb2312 iso etc. It should be fine. Infact i have logged the insert query and run it outside doctrine and it works. I will open an issue on the doctrine dbal project. I will have to move these files outside mysql/doctrine if I keep getting these problems. Thanks again for checking this on your side. I will close the ticket for now
