### ISSUE TITLE
Notice Error

### ISSUE THREAD

**Issue by danielspk** [voku/portable-utf8#50]
Hello, I have this error:

**Notice: Undefined index: mbstring in vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 3811**

mbstring extension is installed.

Thanks.

**Comment by voku** [comment]
already fixed by https://github.com/voku/portable-utf8/commit/728060962337d688536120b12b272a77f25e085a

-> and now there is also a new tag (version) -> 3.1.3
