### ISSUE TITLE
Undefined Variable: text

### ISSUE THREAD

**Issue by cyburgee** [voku/portable-utf8#59]
#### What is this feature about (expected vs actual behaviour)?
Getting this error message when using the latest release:
```ErrorException: Noticed exception 'ErrorException' with message 'Undefined variable: text' in /mnt/deploy/vendor/voku/portable-utf8/src/voku/helper/UTF8.php:7122```
#### How can I reproduce it?
use the `to_utf8` function
#### Does it take minutes, hours or days to fix?
Probably just a copy/paste error.
#### Any additional information?

**Comment by voku** [comment]
Hi, thank you this report ... I reverted some of the last changes, because we need some tests before adding this. 

fixed in version: 3.1.23
