### ISSUE TITLE
Do not use for PHP 5.6

### ISSUE THREAD

**Issue by hoangnamitc** [voku/portable-utf8#60]
Hi @voku ,

I using PHP version 5.6 then class Bootup error function **random_bytes()** (line 164). how to fix problem

random_bytes() => PHP7

I use function **openssl_random_pseudo_bytes()** replace is stability ?

thanks

**Comment by voku** [comment]
Have you installed it via "composer require voku/portable-utf8" ?

-> because we will use "symfony/polyfill" for e.g. random_bytes()

**Comment by hoangnamitc** [comment]
I installed it via:
require "/src/voku/helper/Bootup.php"
require "/src/voku/helper/UTF8.php"

How to Fixed ?

Thanks !

**Comment by voku** [comment]
1. Install composer (https://getcomposer.org/doc/00-intro.md) 

2. Use composer: e.g.:
composer require voku/portable-utf8

2.1 Generate an optimized autoloader
composer dump-autoload -o

3. Include all vendor classes: e.g.:
require __DIR__ . '/vendor/autoload.php';

**Comment by hoangnamitc** [comment]
Thanks for support, but it still does not work:

![image](https://user-images.githubusercontent.com/7042462/29441395-344cc430-83f5-11e7-840f-87ab38917ccd.png)

![image](https://user-images.githubusercontent.com/7042462/29441402-3ea9b974-83f5-11e7-841d-f8f852128a67.png)

![image](https://user-images.githubusercontent.com/7042462/29441405-46a01858-83f5-11e7-9674-ddb3dedd7ada.png)

![image](https://user-images.githubusercontent.com/7042462/29441406-502d544e-83f5-11e7-96a2-5270e9fe697d.png)

**Comment by hoangnamitc** [comment]
My problem has been resolved by:

$class = new voku\helper\

**Comment by voku** [comment]
You can also use the "use" statement. (and you can use aliases: use voku\helper\UTF8 as u;) 

PS: If you need working examples (for any library) take a look at the tests: https://github.com/voku/portable-utf8/blob/master/tests/
