### ISSUE TITLE
Invalid dependency on symfony/polyfill

### ISSUE THREAD

**Issue by Bilge** [voku/portable-utf8#64]
According to the [official documentation](https://github.com/symfony/polyfill#usage):

>When using Composer to manage your dependencies, you should **not** `require` the `symfony/polyfill` package, but the standalone ones

However, this package depends directly on `symfony/polyfill`. Consequently I end up having to download `ircmaxell/password-compat` and `paragonie/random_compat` even though I need neither of them on PHP 7.1, and this package has a minimum constraint of PHP 7.0, which also does not require at least one of them.

**Comment by voku** [comment]
fixed via https://github.com/voku/portable-utf8/commit/64760b4020fa4751e7c60a040dd2173db10137b3
