### ISSUE TITLE
Test failure on Windows

### ISSUE THREAD

**Issue by Bilge** [voku/portable-utf8#65]
There is a consistent test failure on my Windows box, although for some reason it doesn't seem to be picked up by your Appveyor build (that is failing with a different error).

```
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.6 with Xdebug 2.5.0
Configuration: C:\portable-utf8\phpunit.xml
Error:         Incorrect whitelist config, no code coverage will be generated.

...............................................................  63 / 498 ( 12%)
.................................F............................. 126 / 498 ( 25%)
............................................................... 189 / 498 ( 37%)
............................................................... 252 / 498 ( 50%)
............................................................... 315 / 498 ( 63%)
............................................................... 378 / 498 ( 75%)
............................................................... 441 / 498 ( 88%)
.........................................................       498 / 498 (100%)

Time: 17.63 seconds, Memory: 24.00MB

There was 1 failure:

1) Utf8GlobalTest::testFileGetContents
Failed asserting that '\n
Iñtërnâ' contains "Iñtërnât".

C:\portable-utf8\tests\Utf8GlobalTest.php:761
```

It seems to be an off-by-one error but I wasn't able to determine why it seems to pass on other systems such as Travis or why it only affects this one test in particular.

**Comment by voku** [comment]
Good question, I can reproduce the failure via Windows + PHP 7.1 and I think that this is a line feed problem "\n" (Linux) - "\r\n" (windows). Here someone else fixed the problem: https://github.com/orangehill/iseed/pull/79/files

So I think if you edit your "git config --global core.autocrlf" setting (https://github.com/Microsoft/WSL/issues/2318), the tests will be work fine. This is properly also the reason why the tests are working for Appveyor.
