### ISSUE TITLE
How to initialize the "UTF8" class.

### ISSUE THREAD

**Issue by Lovecircle** [voku/portable-utf8#67]
Hello. 

I installed the package via Composer - using composer.json file I found in .zip archive of this package.
Then I wrote a line which includes the package:
        require_once(__DIR__."/../plugins/composer/vendor/autoload.php");

Now, how to initialize the "UTF8" class? - in order to use it like this:
      echo UTF8::fix_utf8('DÃ¼sseldorf');

I cannot find an example in the description of the package.
P.S. I'm new to Composer.

Thank You.

**Comment by voku** [comment]
Hi, the best way to use a package is to take a look at the tests. If there are no tests, then you maybe don't want to use it at all.

PS: do you use the namespace? 
```php
<?php
use voku\helper\UTF8;

require_once(DIR . "/composer/vendor/autoload.php");

echo UTF8::fix_utf8('DÃ¼sseldorf');
```
