### ISSUE TITLE
Update PHP requirements in README.md

### ISSUE THREAD

**Issue by cpeel** [voku/portable-utf8#68]
The Requirements and Recommendations section of the README.md state that PHP 5.3 or higher is required, but according to CHANGELOG.md (and implied in the intro of the README.md) it sounds like PHP 7.0 is now the default.

If that is correct, please update the requirements section to reflect this.

**Comment by voku** [comment]
done... 

Composer will install a older version of "portable-utf8" if you haven't a supported php version or at least PHP 7.0.
