### ISSUE TITLE
Return value of voku\helper\ASCII::getData() must be of the type array

### ISSUE THREAD

**Issue by zgcasas** [voku/portable-utf8#90]
TypeError: Return value of voku\helper\ASCII::getData() must be of the type array, boolean returned in vendor/voku/portable-ascii/src/voku/helper/ASCII.php:759

After update from 5.4.16 to 5.4.20

**Comment by voku** [comment]
"getData" is only used for static files and this files are in the repository... so maybe you haven't read permissions or something like that? Have you a stacktrace of this error?

**Comment by voku** [comment]
Do you know what was the source of the problem?
