### ISSUE TITLE
Incorrect detection of UTF8 string where final byte is in multibyte range

### ISSUE THREAD

**Issue by daniel-jeffery** [voku/portable-utf8#94]
#### What is this feature about (expected vs actual behaviour)?
The UTF8::is_utf8_string function is incorrectly detecting UTF8 encoding when the last byte in a string forms an incomplete multibyte character.

#### How can I reproduce it?
    $input = "Montr\xE9al";
    $output = voku\helper\UTF8::filter($input);
    var_dump($output);
    // Expected output: Montréal
    // Real output: Montréal
    
    $input = "Quantit\xE9";
    $output = voku\helper\UTF8::filter($input);
    var_dump($output);
    // Expected output: Quantité
    // Real output: Quantit�

#### Does it take minutes, hours or days to fix?
Minutes, or hours if my understanding of the problem is incorrect.

#### Any additional information?
In my brief testing, I found that changing the `return true` at the bottom of UTF8::is_utf8_string corrected the issue:

    return $mState == 0;

**Comment by voku** [comment]
Thanks for the good bug report and for the fix. :+1:
