### ISSUE TITLE
Not all features in the readme

### ISSUE THREAD

**Issue by olegatro** [voku/portable-utf8#95]
Hello!

Right now I am using method - `str_truncate_safe` but coudn`t find it in the readme file.

It will be nice to see all available methods in the readme or some other documentation.

**Comment by voku** [comment]
What do you think of this "https://github.com/voku/portable-utf8/blob/master/build/README_TEST.md#class-methods" 

PS: auto-generated via "https://github.com/voku/portable-utf8/blob/master/build/generate_docs.php"

**Comment by olegatro** [comment]
Awesome!

**Comment by olegatro** [comment]
Can I get chat with you personally ? 

In the future , if I need you help

**Comment by olegatro** [comment]
I am from Russia

**Comment by voku** [comment]
Sure, you can write me on twitter "@suckup_de" or via e-mail "lars@moelleken.org" but this week I am a bit busy because I need to take care for my little daughter and I can only program some hours in the evening.

**Comment by voku** [comment]
<s>evening</s> night

**Comment by voku** [comment]
I moved all code examples into the code and auto-generated the main README, so that now all methods are documented.
